# Generated by Django 4.1.1 on 2022-09-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0002_alter_usermessage_user_id_alter_usertoken_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
